### ISSUE TITLE
garages and npwd are not connected

### ISSUE THREAD

**Issue by Fraprwnt** [Qbox-project/npwd_qbx_garages#11]
### Summary

like there was a change that resulted in this not being connected

### Reproduction

![image](https://github.com/Qbox-project/npwd_qbx_garages/assets/58946086/061c415b-970f-4092-81c7-f5ee41d2d444)
after using the latest qbx_garages version npwd_qbx_garages an error appears like this and when in ingame an error in the npwd file on line 34 error global config

### Expected behavior

..

### Actual behavior

.

### Additional context

.

### Current Version

...

### Custom Resources

npwd_qbx_garages

**Comment by Fraprwnt** [comment]
Fixed by @solareon

**Comment by solareon** [comment]
Leaving open until #12 is merged
